on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the git ref is ${{ github.ref }}"
      - run: echo "the git ref name is ${{ github.ref_name}}"
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: release-please-action
