on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: echo "gitref is $GITHUB_REF"
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: release-please-action
